// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJjZeJXP9hTF6AKpwgTNAvzjC5B-wSHWY',
    appId: '1:27994800911:web:c09a6b61886e638484b47a',
    messagingSenderId: '27994800911',
    projectId: 'todo-hti-f26b0',
    authDomain: 'todo-hti-f26b0.firebaseapp.com',
    storageBucket: 'todo-hti-f26b0.appspot.com',
    measurementId: 'G-WQRES4Y08M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPE88GxHyj2IGaci60IJO1BUAgkU9aqf4',
    appId: '1:27994800911:android:87b63e2ead38934084b47a',
    messagingSenderId: '27994800911',
    projectId: 'todo-hti-f26b0',
    storageBucket: 'todo-hti-f26b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWDE6XOWvQSh2Gw1jM245cAvoTw7xI44k',
    appId: '1:27994800911:ios:7364fac5f965e9c184b47a',
    messagingSenderId: '27994800911',
    projectId: 'todo-hti-f26b0',
    storageBucket: 'todo-hti-f26b0.appspot.com',
    iosClientId: '27994800911-2aoifl3jtefot2hjtk6aeronfa5u5djn.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );
}
